name:                peridot
version:             0.1.0.0
github:              "eashanhatti/peridot"
license:             MPL-2.0
author:              "Eashan Hatti"
maintainer:          "eashanhatti@gmail.com"
copyright:           "2022 Eashan Hatti"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/eashanhatti/peridot#readme>

default-extensions:
- GADTs
- ImportQualifiedPost
- GeneralizedNewtypeDeriving
- DerivingStrategies
- RoleAnnotations
- StandaloneDeriving
- DeriveGeneric
- FlexibleInstances
- BlockArguments
- ViewPatterns
- DuplicateRecordFields
- OverloadedLabels
- DisambiguateRecordFields
- ConstraintKinds
- DeriveTraversable
- TypeApplications
- OverloadedStrings
- FlexibleContexts
- LambdaCase
- ScopedTypeVariables
- BangPatterns
- PackageImports
- TupleSections
- RecursiveDo
- EmptyDataDeriving
- PatternSynonyms
- MonadComprehensions
- RankNTypes

dependencies:
- base >=4.0 && <5
- text
- mtl
- containers
- some
- dependent-hashmap 
- dependent-sum
- hashable
- fused-effects
- extra
- megaparsec
- parser-combinators
- tasty-golden
- tasty
- bytestring
- filepath
- shower
- parser-combinators

library:
  source-dirs: src

executables:
  peridot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - peridot

tests:
  peridot-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - peridot
